begin;
select plan(18);
select has_schema('private', 'private schema exists');
select has_schema('api', 'api schema exists');
select has_table('public','contacts','contacts is canonical person entity');
select has_table('public','opportunities','opportunities roots pipeline');
select has_table('public','proposals','proposals are separate');
select has_table('public','contracts','contracts are separate');
select has_table('private','integration_credentials','credentials are private');
select has_table('private','idempotency_receipts','receipts are private');
select has_view('api','attendance_queue','attendance is read model');
select has_view('api','contact_pipeline_summary','pipeline read model exists');
select col_is_pk('public','lead_distribution_settings','organization_id','settings use organization primary key');
select col_is_pk('public','goal_settings','organization_id','goal settings use organization primary key');
select col_is_unique('public','contacts','organization_id','contacts tenant identity is unique');
select col_is_unique('public','properties','public_code','properties have public code uniqueness');
select fk_ok('public','contacts','organization_id','public','organizations','id','contacts tenant FK');
select fk_ok('public','properties','organization_id','public','organizations','id','properties tenant FK');
select ok((select relrowsecurity from pg_class where oid='public.contacts'::regclass),'contacts RLS enabled');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('portal_create_lead','feed_properties')),'legacy RPCs absent');
select * from finish();
rollback;
