insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('properties','properties',true,15728640,array['image/jpeg','image/png','image/webp']),
 ('site-assets','site-assets',true,15728640,array['image/jpeg','image/png','image/webp']),
 ('documents-private','documents-private',false,26214400,array['application/pdf'])
on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy properties_public_read on storage.objects for select to anon,authenticated using (bucket_id='properties');
create policy properties_manager_insert on storage.objects for insert to authenticated with check (
  bucket_id='properties' and (select private.current_role()) in ('owner','manager') and (storage.foldername(name))[1]='org' and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='properties' and exists (select 1 from public.properties p where p.organization_id=(select private.current_org_id()) and p.id=private.path_uuid((storage.foldername(name))[4]))
);
create policy properties_broker_insert on storage.objects for insert to authenticated with check (
  bucket_id='properties' and (select private.current_role())='broker' and (storage.foldername(name))[2]=(select private.current_org_id())::text and exists (select 1 from public.properties p where p.organization_id=(select private.current_org_id()) and p.id=private.path_uuid((storage.foldername(name))[4]) and p.assigned_to=(select auth.uid()))
);
create policy properties_manager_update on storage.objects for update to authenticated using (bucket_id='properties' and (select private.current_role()) in ('owner','manager') and (storage.foldername(name))[2]=(select private.current_org_id())::text) with check (bucket_id='properties' and (storage.foldername(name))[2]=(select private.current_org_id())::text);
create policy properties_broker_update on storage.objects for update to authenticated using (bucket_id='properties' and (select private.current_role())='broker' and (storage.foldername(name))[2]=(select private.current_org_id())::text and exists(select 1 from public.properties p where p.organization_id=(select private.current_org_id()) and p.id=private.path_uuid((storage.foldername(name))[4]) and p.assigned_to=(select auth.uid()))) with check (bucket_id='properties' and (storage.foldername(name))[2]=(select private.current_org_id())::text);
create policy properties_manager_delete on storage.objects for delete to authenticated using (bucket_id='properties' and (select private.current_role()) in ('owner','manager') and (storage.foldername(name))[2]=(select private.current_org_id())::text);
create policy properties_broker_delete on storage.objects for delete to authenticated using (bucket_id='properties' and (select private.current_role())='broker' and (storage.foldername(name))[2]=(select private.current_org_id())::text and exists(select 1 from public.properties p where p.organization_id=(select private.current_org_id()) and p.id=private.path_uuid((storage.foldername(name))[4]) and p.assigned_to=(select auth.uid())));

create policy site_assets_public_read on storage.objects for select to anon,authenticated using (bucket_id='site-assets');
create policy site_assets_manager_write on storage.objects for all to authenticated using (bucket_id='site-assets' and (select private.current_role()) in ('owner','manager') and (storage.foldername(name))[1]='org' and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='site') with check (bucket_id='site-assets' and (storage.foldername(name))[1]='org' and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='site');

create policy private_documents_manager_read on storage.objects for select to authenticated using (bucket_id='documents-private' and (select private.current_role()) in ('owner','manager') and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='contracts' and exists(select 1 from public.contracts c where c.organization_id=(select private.current_org_id()) and c.id=private.path_uuid((storage.foldername(name))[4])));
create policy private_documents_broker_read on storage.objects for select to authenticated using (bucket_id='documents-private' and (select private.current_role())='broker' and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='contracts' and exists(select 1 from public.contracts c where c.organization_id=(select private.current_org_id()) and c.id=private.path_uuid((storage.foldername(name))[4]) and c.assigned_to=(select auth.uid())));
create policy private_documents_manager_write on storage.objects for all to authenticated using (bucket_id='documents-private' and (select private.current_role()) in ('owner','manager') and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='contracts' and exists(select 1 from public.contracts c where c.organization_id=(select private.current_org_id()) and c.id=private.path_uuid((storage.foldername(name))[4]))) with check (bucket_id='documents-private' and (storage.foldername(name))[2]=(select private.current_org_id())::text and (storage.foldername(name))[3]='contracts');
